export const NOTIFICATION_TYPES = Object.freeze({
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_REMINDER: 'BOOKING_REMINDER',
  MATCH_EXPIRED_UNDERFILLED: 'MATCH_EXPIRED_UNDERFILLED',
  MATCH_CANCELLED: 'MATCH_CANCELLED',
  GROUP_JOIN_REQUEST: 'GROUP_JOIN_REQUEST',
  GROUP_APPROVED: 'GROUP_APPROVED',
  GROUP_REJECTED: 'GROUP_REJECTED',
  GROUP_KICKED: 'GROUP_KICKED',
  GROUP_ADMIN_TRANSFERRED: 'GROUP_ADMIN_TRANSFERRED',
  SYSTEM: 'SYSTEM',
});

export const REMINDER_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  CANCELLED: 'CANCELLED',
  FAILED: 'FAILED',
});

export const REMINDER_OFFSET_HOURS = Object.freeze([24, 2]);

export const NOTIF_REMINDERS_REDIS_KEY = 'notif:reminders';

export const REMINDER_WORKER_INTERVAL_MS =
  Number(process.env.REMINDER_WORKER_INTERVAL_MS) || 15_000;
