export const PAYMENT_PROVIDERS = Object.freeze({
  VNPAY: 'VNPAY',
  MOMO: 'MOMO',
});

export const TRANSACTION_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
});

export const ACTIVE_TRANSACTION_STATUSES = Object.freeze([
  TRANSACTION_STATUSES.PENDING,
  TRANSACTION_STATUSES.SUCCESS,
]);

export const DEFAULT_PAYMENT_TTL_SECONDS = 900;
