export const colors = {
  primary: '#2F4CDD',
  primarySoft: '#E7ECFB',
  background: '#FFFFFF',
  screenBackground: '#F3F4F6',
  text: '#1A1A1A',
  subtitle: '#6B7280',
  placeholder: '#9CA3AF',
  border: '#D1D5DB',
  error: '#DC2626',
  required: '#DC2626',
  white: '#FFFFFF',
  pink: '#EC4899',
  pinkSoft: '#FDF2F8',
  orange: '#F97316',
  orangeSoft: '#FFF7ED',
  amber: '#F59E0B',
  amberSoft: '#FFFBEB',
};
